json.(@vault_hunter, :created_at, :updated_at)
json.name = @vault_hunter.name
json.user_id = @vault_hunter.user_id
json.age = @vault_hunter.age
json.race = @vault_hunter.race
json.height = @vault_hunter.height
json.weight = @vault_hunter.weight
json.toughness = @vault_hunter.toughness
json.wounds = @vault_hunter.wounds
json.shields = @vault_hunter.shield
json.current_shield = @vault_hunter.current_shield
json.loot = @vault_hunter.loot
json.money = @vault_hunter.money
json.level = @vault_hunter.level
json.current_proficiency_points = @vault_hunter.current_proficiency_points
json.current_skill_points = @vault_hunter.current_skill_points